services:
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - app

    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/static:ro
      - ./images:/images
  app:
    build: ./
    container_name: app
    ports:
      - "8000:8000"
    environment:
      - LOG_DIR=/logs
    volumes:
      - ./images:/app/images
      - ./logs:/logs

  
  
