services:
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - app

    ports:
      - "8080:8080"

    restart: unless-stopped

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/static:ro
      - ./images:/images
  app:
    build: ./
    container_name: app
    ports:
      - "8000:8000"

    restart: unless-stopped
    
    environment:
      - LOG_DIR=/logs
    volumes:
      - ./images:/app/images
      - ./logs:/logs
  db:
    image: postgres:18-alpine
    shm_size: '128mb'
    restart: unless-stopped
    container_name: db
    environment:
      POSTGRES_USER: images_backend
      POSTGRES_PASSWORD: 1048575
      POSTGRES_DB: images_hosting
    
    # ports:
    #   - "5432:5432"
    
    # volumes:
    #   - ./db_data:/var/lib/postgresql/data
  
  
