server {
    listen 80;
    client_max_body_size 6m;

    location /images/ {
        alias /usr/share/nginx/images/;
    }

    location / {
        proxy_pass http://app:8080;
        proxy_set_header Host $host;
    }
}